version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run build
          command: yarn build
      - run:
          name: Run export
          command: yarn export
      - run:
          name: Run deploy
          command: node gh-pages.j
